version: '3.4'

services:
  test:
    container_name: test
    image: mcr.microsoft.com/dotnet/sdk:2.1
    volumes:
      - .:/app
    working_dir: /app
    command:
      [
        "dotnet",
        "test",
        "Test/Test.csproj"
      ]
