name: TestingAndLinting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Execute tests
        working-directory: ./
        run: docker-compose run test
  lint:
      runs-on: ubuntu-latest
      steps:
       - name: Super-Linter
         uses: github/super-linter@v4.8.4
         env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
